### PR TITLE
Debug info, max of 360 degrees, simplified controls, GUI

### PR DESCRIPTION
**Pull request by Fuzss**
Added a few entries in the debug menu, they'll only be visible when the orthographic camera is.
Both rotation values now have a max of 360 degrees since they are visible in the debug screen.
Removed some controls, their functionality is still available through the presets toggle.

### CODE REVIEW

**Comment by ata4** [comment]
Thanks! Wow, that's a lot of changes. I'll review that this weekend when I'll have more time.

**Comment by Fuzss** [comment]
I just saw there are already changes in here that aren’t finished yet (I’m talking about this whole gui thingy, I just started working on this). I’ll take them out again tomorrow and will create another pull request when I’m done. 

I would understand if you don’t like the new controls since they aren’t like in Blender anymore, but I think they’re more user friendly. But they aren’t very crucial. Main thing I’d really like you to add is the debug screen entry since it helps so much when working with the orthographic view.

**Comment by Fuzss** [comment]
Ok, that's it for now. I've removed the code that shouldn't have been in here already. I've also made some further improvements to my additions and let two friends from the Minecraft Wiki help out with the translations.
Now I'm just curious for what you will have to say when you get a chance to take a closer look.

**Comment by Fuzss** [comment]
I was able to finish the GUI I mentioned earlier by now. It's included in this pull request. I also improved my previous additions and changed some other minor things. I hope you like it.

**Comment by ata4** [comment]
Hm... there's an issue with the Gradle script, I think I have to update something first before I can build this. I think it'll take a bit longer, sorry.

**Comment by Fuzss** [comment]
I noticed that. I updated it on my fork. You can take it from there if you want a working version.

**Comment by Fuzss** [comment]
I've now spent some more time working on the GUI adding reset buttons, a focus mode and tooltips. I've also changed a few minor things with the orthographic camera itself that have annoyed me for some time, I hope you like those changes. But that's really it now, I'm kinda sorry for giving you more and more that you'll have to go through. ^^

**Pull request closed without merging**
